-- DEPRECATED
-- Canonical RBAC/security implementation now lives in:
-- supabase/migrations/20261001_rbac_security_consolidation.sql
--
-- Do not run this file on an existing deployment. It was the original
-- one-shot RBAC bootstrap and can redefine policies/functions that are now
-- managed by migrations.
-- Kept as a historical reference.