(() => {
  const url = window.DMP_SUPABASE_URL;
  const key = window.DMP_SUPABASE_ANON_KEY;
  const enabled = Boolean(url && key && window.supabase);
  const client = enabled ? window.supabase.createClient(url, key) : null;
  let currentUser = null;
  let loggingOut = false;
  const emit = (type, detail = {}) => window.dispatchEvent(new CustomEvent(type, { detail }));
  const configMessage = !enabled ? 'الحسابات السحابية غير مفعلة بعد. ضع Supabase URL و anon key في supabase-config.js.' : '';
  function closeAuth(){const m=document.getElementById('authModal');if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true');m.style.display='none';m.style.visibility='hidden';m.style.pointerEvents='none';document.body.classList.remove('auth-open');}
  function resetAccountButton(){const a=document.getElementById('accountArea');if(!a)return;a.innerHTML='<button class="account-btn" id="accountBtn" type="button">👤 حسابي</button>';const b=document.getElementById('accountBtn');if(b)b.onclick=openAuth;}
  function showLoggedOut(){currentUser=null;closeAuth();resetAccountButton();}
  function ensureUi(){if(document.getElementById('accountArea'))return;const nav=document.querySelector('.nav');if(!nav)return;const area=document.createElement('div');area.id='accountArea';area.className='account-area';area.innerHTML='<button class="account-btn" id="accountBtn" type="button">👤 حسابي</button>';nav.insertBefore(area,document.getElementById('themeBtn'));const modal=document.createElement('div');modal.id='authModal';modal.className='auth-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="auth-box" role="dialog" aria-modal="true"><button class="auth-close" id="authClose" type="button">×</button><span class="eyebrow">DIGITAL MARKETING PRO</span><h2>حساب المتعلم</h2><p class="auth-note" id="authNote">سجّل الدخول لحفظ تقدمك على أي جهاز.</p><label>البريد الإلكتروني<input id="authEmail" type="email"></label><label>كلمة المرور<input id="authPassword" type="password"></label><div class="auth-actions"><button class="btn primary" id="loginBtn" type="button">تسجيل الدخول</button><button class="btn ghost" id="signupBtn" type="button">إنشاء حساب</button></div><button class="auth-link" id="resetBtn" type="button">نسيت كلمة المرور؟</button><p class="auth-status" id="authStatus"></p></div>`;document.body.appendChild(modal);document.getElementById('accountBtn').onclick=openAuth;document.getElementById('authClose').onclick=closeAuth;modal.addEventListener('click',e=>{if(e.target===modal)closeAuth()});document.getElementById('loginBtn').onclick=signIn;document.getElementById('signupBtn').onclick=signUp;document.getElementById('resetBtn').onclick=resetPassword;}
  function setStatus(t,ok=false){const e=document.getElementById('authStatus');if(e){e.textContent=t;e.classList.toggle('ok',ok)}}
  function openAuth(){ensureUi();const m=document.getElementById('authModal');if(!m)return;m.style.visibility='visible';m.style.pointerEvents='auto';m.style.display='grid';m.classList.add('show');m.setAttribute('aria-hidden','false');if(!enabled)return setStatus(configMessage);if(currentUser&&!loggingOut)showAccount();else document.getElementById('authEmail')?.focus();}
  function showAccount(){if(loggingOut)return;const n=document.getElementById('authNote'),a=document.querySelector('.auth-actions'),r=document.getElementById('resetBtn'),e=document.getElementById('authEmail'),p=document.getElementById('authPassword');if(!currentUser||!n||!a||!e||!p||!r)return;n.textContent=`مسجل الدخول: ${currentUser.email}`;e.style.display='none';p.style.display='none';r.style.display='none';a.innerHTML='<button class="btn primary" id="syncNow" type="button">مزامنة التقدم ☁️</button><button class="btn ghost" id="logoutBtn" type="button">تسجيل الخروج</button>';document.getElementById('syncNow').onclick=async()=>{await saveProgress(JSON.parse(localStorage.getItem('dmp-state')||'{}'));setStatus('تمت مزامنة التقدم بنجاح ✅',true)};document.getElementById('logoutBtn').onclick=signOut;}
  function signOut(){if(loggingOut)return;loggingOut=true;currentUser=null;closeAuth();resetAccountButton();emit('dmp-logged-out');if(enabled&&client){client.auth.signOut({scope:'local'}).catch(e=>console.error('Logout error:',e)).finally(()=>{loggingOut=false})}else loggingOut=false;}
  window.DMP_logout=signOut;window.DMP_closeAuth=closeAuth;window.DMP_openAuth=openAuth;
  async function signIn(){if(!enabled)return setStatus(configMessage);const e=document.getElementById('authEmail').value.trim(),p=document.getElementById('authPassword').value;if(!e||!p)return setStatus('دخل البريد الإلكتروني وكلمة المرور.');setStatus('جاري تسجيل الدخول...');const{error}=await client.auth.signInWithPassword({email:e,password:p});if(error)return setStatus(error.message);closeAuth();}
  async function signUp(){if(!enabled)return setStatus(configMessage);const e=document.getElementById('authEmail').value.trim(),p=document.getElementById('authPassword').value;if(!e||p.length<6)return setStatus('استعمل بريد صحيح وكلمة مرور من 6 أحرف على الأقل.');setStatus('جاري إنشاء الحساب...');const{data,error}=await client.auth.signUp({email:e,password:p});if(error)return setStatus(error.message);if(!data.session)return setStatus('تم إنشاء الحساب. راجع بريدك لتأكيد الحساب ثم سجل الدخول.',true);closeAuth();}
  async function resetPassword(){if(!enabled)return setStatus(configMessage);const e=document.getElementById('authEmail').value.trim();if(!e)return setStatus('دخل البريد الإلكتروني أولاً.');const{error}=await client.auth.resetPasswordForEmail(e,{redirectTo:location.origin+location.pathname});setStatus(error?error.message:'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك.',!error)}
  async function loadProgress(u){if(!enabled||!u)return;const{data,error}=await client.from('course_progress').select('state').eq('user_id',u.id).maybeSingle();if(error)return;if(data?.state){localStorage.setItem('dmp-state',JSON.stringify(data.state));emit('dmp-cloud-state',{state:data.state})}else await saveProgress(JSON.parse(localStorage.getItem('dmp-state')||'{}'))}
  async function saveProgress(s){if(!enabled||!currentUser)return;await client.from('course_progress').upsert({user_id:currentUser.id,state:s,updated_at:new Date().toISOString()})}
  window.DMP_saveState=saveProgress;window.DMP_cloudEnabled=enabled;
  document.addEventListener('DOMContentLoaded',async()=>{ensureUi();if(!enabled)return;const{data}=await client.auth.getSession();currentUser=data.session?.user||null;if(currentUser){showAccount();await loadProgress(currentUser)}client.auth.onAuthStateChange((_event,session)=>{if(loggingOut)return;currentUser=session?.user||null;if(currentUser){ensureUi();showAccount();loadProgress(currentUser).catch(()=>{})}else showLoggedOut()})});
})();