(() => {
  const url = window.DMP_SUPABASE_URL;
  const key = window.DMP_SUPABASE_ANON_KEY;
  const enabled = Boolean(url && key && window.supabase);
  const client = enabled ? window.supabase.createClient(url, key) : null;
  let currentUser = null;
  let loggingOut = false;
  const emit = (type, detail = {}) => window.dispatchEvent(new CustomEvent(type, { detail }));
  function closeAuth() { const modal=document.getElementById('authModal'); if(!modal)return; modal.classList.remove('show'); modal.setAttribute('aria-hidden','true'); modal.style.display='none'; modal.style.visibility='hidden'; modal.style.opacity='0'; modal.style.pointerEvents='none'; document.body.classList.remove('auth-open'); }
  function resetAccountButton(){const area=document.getElementById('accountArea');if(!area)return;area.innerHTML='<button class="account-btn" id="accountBtn" type="button">👤 حسابي</button>';const b=document.getElementById('accountBtn');if(b)b.onclick=openAuth;}
  function showLoggedOut(){currentUser=null;closeAuth();resetAccountButton();}
  function ensureUi(){if(document.getElementById('accountArea'))return;const nav=document.querySelector('.nav');if(!nav)return;const area=document.createElement('div');area.id='accountArea';area.className='account-area';area.innerHTML='<button class="account-btn" id="accountBtn" type="button">👤 حسابي</button>';nav.insertBefore(area,document.getElementById('themeBtn'));const modal=document.createElement('div');modal.id='authModal';modal.className='auth-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="auth-box" role="dialog" aria-modal="true"><button class="auth-close" id="authClose" type="button">×</button><span class="eyebrow">DIGITAL MARKETING PRO</span><h2>حساب المتعلم</h2><p class="auth-note" id="authNote">سجّل الدخول لحفظ تقدمك على أي جهاز.</p><label>البريد الإلكتروني<input id="authEmail" type="email"></label><label>كلمة المرور<input id="authPassword" type="password"></label><div class="auth-actions"><button class="btn primary" id="loginBtn" type="button">تسجيل الدخول</button><button class="btn ghost" id="signupBtn" type="button">إنشاء حساب</button></div><button class="auth-link" id="resetBtn" type="button">نسيت كلمة المرور؟</button><p class="auth-status" id="authStatus"></p></div>`;document.body.appendChild(modal);document.getElementById('accountBtn').onclick=openAuth;document.getElementById('authClose').onclick=closeAuth;document.getElementById('loginBtn').onclick=signIn;document.getElementById('signupBtn').onclick=signUp;document.getElementById('resetBtn').onclick=resetPassword;modal.addEventListener('click',e=>{if(e.target===modal)closeAuth();});}
  function setStatus(text,ok=false){const el=document.getElementById('authStatus');if(el){el.textContent=text;el.classList.toggle('ok',ok);}}
  function openAuth(){ensureUi();const modal=document.getElementById('authModal');if(!modal)return;modal.style.display='grid';modal.style.visibility='visible';modal.style.opacity='1';modal.style.pointerEvents='auto';modal.classList.add('show');modal.setAttribute('aria-hidden','false');if(!enabled)return setStatus('الحسابات السحابية غير مفعلة بعد. ضع Supabase URL و anon key في supabase-config.js.');if(currentUser&&!loggingOut)showAccount();else document.getElementById('authEmail')?.focus();}
  function showAccount(){if(loggingOut||!currentUser)return;const n=document.getElementById('authNote'),a=document.querySelector('.auth-actions'),r=document.getElementById('resetBtn'),e=document.getElementById('authEmail'),p=document.getElementById('authPassword');if(!n||!a||!r||!e||!p)return;n.textContent=`مسجل الدخول: ${currentUser.email}`;e.style.display='none';p.style.display='none';r.style.display='none';a.innerHTML='<button class="btn primary" id="syncNow" type="button">مزامنة التقدم ☁️</button><button class="btn ghost" id="logoutBtn" type="button">تسجيل الخروج</button>';document.getElementById('syncNow').onclick=async()=>{await saveProgress(JSON.parse(localStorage.getItem('dmp-state')||'{}'));setStatus('تمت مزامنة التقدم بنجاح ✅',true);};document.getElementById('logoutBtn').onclick=signOut;}
  function signOut(event){if(event){event.preventDefault();event.stopPropagation();}if(loggingOut)return false;loggingOut=true;currentUser=null;closeAuth();resetAccountButton();emit('dmp-logged-out');if(enabled&&client){Promise.resolve(client.auth.signOut({scope:'local'})).catch(err=>console.error('Logout error:',err)).finally(()=>{loggingOut=false;});}else loggingOut=false;return false;}
  document.addEventListener('click',e=>{const btn=e.target?.closest?.('#logoutBtn');if(btn&&!loggingOut)signOut(e);});
  window.DMP_logout=signOut;window.DMP_closeAuth=closeAuth;window.DMP_openAuth=openAuth;window.DMP_saveState=saveProgress;window.DMP_cloudEnabled=enabled;
  async function signIn(){if(!enabled)return setStatus('الحسابات السحابية غير مفعلة بعد.');const e=document.getElementById('authEmail')?.value.trim(),p=document.getElementById('authPassword')?.value||'';if(!e||!p)return setStatus('دخل البريد الإلكتروني وكلمة المرور.');setStatus('جاري تسجيل الدخول...');const{error}=await client.auth.signInWithPassword({email:e,password:p});if(error)return setStatus(error.message);closeAuth();}
  async function signUp(){if(!enabled)return setStatus('الحسابات السحابية غير مفعلة بعد.');const e=document.getElementById('authEmail')?.value.trim(),p=document.getElementById('authPassword')?.value||'';if(!e||p.length<6)return setStatus('استعمل بريد صحيح وكلمة مرور من 6 أحرف على الأقل.');setStatus('جاري إنشاء الحساب...');const{data,error}=await client.auth.signUp({email:e,password:p});if(error)return setStatus(error.message);if(!data.session)return setStatus('تم إنشاء الحساب. راجع بريدك لتأكيد الحساب ثم سجل الدخول.',true);closeAuth();}
  async function resetPassword(){if(!enabled)return setStatus('الحسابات السحابية غير مفعلة بعد.');const e=document.getElementById('authEmail')?.value.trim();if(!e)return setStatus('دخل البريد الإلكتروني أولاً.');const{error}=await client.auth.resetPasswordForEmail(e,{redirectTo:location.origin+location.pathname});setStatus(error?error.message:'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك.',!error);}
  async function loadProgress(u){if(!enabled||!u)return;const{data,error}=await client.from('course_progress').select('state').eq('user_id',u.id).maybeSingle();if(error)return;if(data?.state){localStorage.setItem('dmp-state',JSON.stringify(data.state));emit('dmp-cloud-state',{state:data.state});}else await saveProgress(JSON.parse(localStorage.getItem('dmp-state')||'{}'));}
  async function saveProgress(state){if(!enabled||!currentUser)return;await client.from('course_progress').upsert({user_id:currentUser.id,state,updated_at:new Date().toISOString()});}
  document.addEventListener('DOMContentLoaded',async()=>{ensureUi();if(!enabled)return;const{data}=await client.auth.getSession();currentUser=data.session?.user||null;if(currentUser){showAccount();await loadProgress(currentUser);}client.auth.onAuthStateChange((_event,session)=>{if(loggingOut)return;currentUser=session?.user||null;if(currentUser){ensureUi();showAccount();loadProgress(currentUser).catch(()=>{});}else showLoggedOut();});});
})();
