const modules=[
{n:'01',t:'أساسيات التسويق الرقمي',d:'Marketing fundamentals، customer journey، السوق والمنافسة.',lessons:['ما هو Digital Marketing؟','Customer Journey','Target Audience & Market Research'],quiz:['التسويق الرقمي يعتمد فقط على الإعلانات المدفوعة.','Buyer Persona تساعدك على فهم العميل المستهدف.','Customer Journey تصف مراحل انتقال العميل نحو الشراء.'],answers:[false,true,true],task:'أنشئ Buyer Persona لمنتج أو خدمة تختارها.'},
{n:'02',t:'الاستراتيجية وبناء الخطة',d:'Goals، positioning، personas وmarketing funnel.',lessons:['SMART Goals','Positioning & Value Proposition','Marketing Funnel'],quiz:['SMART هدف قابل للقياس.','Funnel يتوقف عند أول زيارة للموقع.','Positioning يحدد كيف تريد أن يراك السوق.'],answers:[true,false,true],task:'اكتب 3 أهداف SMART وخريطة Funnel بسيطة.'},
{n:'03',t:'الهوية والعلامة التجارية',d:'Brand identity، value proposition وtone of voice.',lessons:['Brand Identity','Value Proposition','Tone of Voice'],quiz:['الهوية تشمل الصورة والرسالة والأسلوب.','Tone of Voice هو سعر المنتج.','Value Proposition تشرح القيمة التي يحصل عليها العميل.'],answers:[true,false,true],task:'أنشئ Brand Brief من صفحة واحدة.'},
{n:'04',t:'Content Marketing',d:'Content strategy، storytelling، calendar وdistribution.',lessons:['Content Strategy','Copywriting & Storytelling','Content Calendar'],quiz:['المحتوى الناجح يبدأ بهدف وجمهور واضح.','كل المحتوى يجب أن يكون إعلاناً مباشراً.','Content Calendar يساعد على التنظيم والاستمرارية.'],answers:[true,false,true],task:'صمم تقويم محتوى لـ7 أيام.'},
{n:'05',t:'Social Media Marketing',d:'Facebook، Instagram، TikTok، LinkedIn وإدارة المجتمع.',lessons:['Platform Strategy','Organic Content','Community Management'],quiz:['نفس المحتوى يعمل دائماً بنفس الطريقة على كل منصة.','التفاعل جزء من بناء المجتمع.','اختيار المنصة يجب أن يرتبط بالجمهور.'],answers:[false,true,true],task:'اختر منصتين وحدد لكل واحدة 3 أنواع محتوى.'},
{n:'06',t:'SEO من الصفر',d:'Keyword research، on-page، technical وlink building.',lessons:['Keyword Research','On-Page SEO','Technical SEO'],quiz:['Keyword Research يساعد على اكتشاف نية البحث.','Title وheading structure لا علاقة لهما بالصفحة.','سرعة وتجربة الموقع من جوانب SEO التقنية.'],answers:[true,false,true],task:'اختر 10 كلمات مفتاحية ورتبها حسب نية البحث.'},
{n:'07',t:'Google Ads',d:'Search، Display، YouTube، bidding وقياس النتائج.',lessons:['Campaign Structure','Keywords & Ads','Bidding & Conversion Tracking'],quiz:['Conversion Tracking ضروري لقياس النتائج.','كل كلمة مفتاحية لها نفس نية البحث.','الإعلان الجيد يجب أن يتوافق مع صفحة الهبوط.'],answers:[true,false,true],task:'اكتب حملة Search من 3 مجموعات إعلانية.'},
{n:'08',t:'Meta Ads',d:'Campaign structure، targeting، creatives وretargeting.',lessons:['Campaign Objectives','Audiences','Creatives & Retargeting'],quiz:['Retargeting يستهدف أشخاصاً تفاعلوا سابقاً.','Creative لا يؤثر على أداء الإعلان.','اختبار أكثر من Creative يساعد على التعلم.'],answers:[true,false,true],task:'صمم هيكلة Campaign مع جمهور بارد وRetargeting.'},
{n:'09',t:'Landing Pages & CRO',d:'UX، copywriting، CTAs، A/B testing والتحويل.',lessons:['Landing Page Anatomy','Persuasive Copy','A/B Testing'],quiz:['CTA واضح يساعد على التحويل.','A/B Test يقارن نسختين لمعرفة الأفضل.','صفحة الهبوط تحتاج دائماً عشرات الأزرار.'],answers:[true,true,false],task:'ابنِ Wireframe لصفحة Landing Page.'},
{n:'10',t:'Email Marketing',d:'Lead magnets، automation، segmentation وretention.',lessons:['Lead Magnet','Email Sequence','Segmentation & Retention'],quiz:['Segmentation يسمح برسائل أكثر ملاءمة.','Email Marketing ينتهي بمجرد جمع البريد.','Automation يمكنه تشغيل رسائل حسب سلوك المستخدم.'],answers:[true,false,true],task:'اكتب Sequence من 5 رسائل لعميل جديد.'},
{n:'11',t:'Analytics & AI',d:'GA4، UTM، dashboards وAI workflows للمسوّق.',lessons:['KPIs & GA4','UTM Tracking','AI Marketing Workflows'],quiz:['UTM تساعد في معرفة مصدر الزيارات.','كل Metric يعتبر KPI مهما كان الهدف.','AI يمكنه تسريع البحث وصناعة الأفكار مع مراجعة بشرية.'],answers:[true,false,true],task:'حدد 8 KPIs وابنِ تصور Dashboard أسبوعي.'},
{n:'12',t:'مشروع التخرج — Digital Marketing Pro',d:'استراتيجية كاملة، حملة، dashboard وPortfolio.',lessons:['Project Brief','Campaign Launch Plan','Final Portfolio'],quiz:['المشروع النهائي يجب أن يربط الاستراتيجية بالتنفيذ والقياس.','Portfolio قوي يعرض النتائج والمنهجية.','لا تحتاج إلى توثيق ما تعلمته.'],answers:[true,true,false],task:'أنجز مشروعاً كاملاً: Strategy + Content + Campaign + Analytics + Portfolio.'}
];
const box=document.querySelector('#modules');
let state=JSON.parse(localStorage.getItem('dmp-state')||'{}');
state.done=state.done||[];state.scores=state.scores||{};
function persistState(){localStorage.setItem('dmp-state',JSON.stringify(state));if(typeof window.DMP_saveState==='function')window.DMP_saveState(state)}
function render(){box.innerHTML=modules.map((m,i)=>`<article class="module ${state.done.includes(i)?'done':''}" data-i="${i}"><div class="module-top"><span class="num">MODULE ${m.n}</span><span class="check">${state.done.includes(i)?'✓':''}</span></div><h3>${m.t}</h3><p>${m.d}</p><div class="module-meta"><span>${m.lessons.length} دروس</span><span>${m.quiz.length} أسئلة</span><button class="openLesson" type="button">فتح الوحدة</button></div></article>`).join('');updateProgress()}
function updateProgress(){const pct=Math.round(state.done.length/modules.length*100);document.querySelector('#progressBar').style.width=pct+'%';document.querySelector('#progressText').textContent=pct+'% مكتمل';document.querySelector('#heroProgress').textContent=pct+'%'}
function openModule(i){const m=modules[i],view=document.querySelector('#lessonView');view.innerHTML=`<span class="eyebrow">MODULE ${m.n}</span><h2>${m.t}</h2><p class="modal-desc">${m.d}</p><h3>📚 الدروس</h3><div class="lesson-list">${m.lessons.map((x,j)=>`<button class="lesson-item" type="button" data-lesson="${j}"><b>${j+1}</b><span>${x}</span><span class="lesson-arrow">←</span></button>`).join('')}</div><div id="lessonContent" class="lesson-content" aria-live="polite"><b>اختر درساً من القائمة 👆</b><p>اضغط على أي درس لفتحه ومتابعة المحتوى.</p></div><div class="task"><b>🎯 التطبيق العملي</b><p>${m.task}</p></div><h3>🧠 اختبار سريع</h3><div id="quiz">${m.quiz.map((q,j)=>`<label class="q"><span>${j+1}. ${q}</span><select data-q="${j}"><option value="">اختر الإجابة</option><option value="true">صحيح</option><option value="false">خطأ</option></select></label>`).join('')}</div><div class="modal-actions"><button class="btn primary" id="finishQuiz">تصحيح وإكمال الوحدة ✓</button><span id="quizResult"></span></div>`;document.querySelector('#lessonModal').classList.add('show');document.querySelector('#lessonModal').setAttribute('aria-hidden','false');document.querySelector('#finishQuiz').onclick=()=>finish(i);document.querySelectorAll('.lesson-item').forEach((el,j)=>el.addEventListener('click',()=>openLesson(i,j)))}
function openLesson(i,j){const m=modules[i],title=m.lessons[j],content=document.querySelector('#lessonContent');if(!content)return;document.querySelectorAll('.lesson-item').forEach((el,k)=>el.classList.toggle('active',k===j));content.innerHTML=`<div class="lesson-content-head"><span>الدرس ${j+1} من ${m.lessons.length}</span><span>📖</span></div><h3>${title}</h3><p>هذا الدرس جزء من وحدة <strong>${m.t}</strong>. ركّز على المفاهيم الأساسية، ثم طبّق ما تعلمته في التمرين العملي واختبر فهمك في الأسئلة الموجودة أسفل الوحدة.</p><div class="lesson-tip">💡 <b>نصيحة:</b> دوّن أهم 3 أفكار من هذا الدرس قبل الانتقال للدرس التالي.</div>`;content.scrollIntoView({behavior:'smooth',block:'nearest'})}
function finish(i){const m=modules[i];let score=0;document.querySelectorAll('#quiz select').forEach((s,j)=>{if(s.value!==''&&s.value===String(m.answers[j]))score++});const result=document.querySelector('#quizResult');result.textContent=`النتيجة: ${score}/${m.quiz.length}`;if(score>=Math.ceil(m.quiz.length*.66)){if(!state.done.includes(i))state.done.push(i);state.scores[i]=score;persistState();render();result.textContent+=` — ممتاز! الوحدة مكتملة 🎉`}else result.textContent+=' — حاول مرة أخرى حتى تحصل على 2/3 على الأقل.'}
window.addEventListener('dmp-cloud-state',e=>{if(e.detail?.state){state=e.detail.state;state.done=state.done||[];state.scores=state.scores||{};render()}});
box.addEventListener('click',e=>{const card=e.target.closest('.module');if(!card)return;if(e.target.closest('.openLesson')){openModule(+card.dataset.i)}});
document.querySelector('#closeModal').onclick=()=>closeModal();document.querySelector('#lessonModal').addEventListener('click',e=>{if(e.target.id==='lessonModal')closeModal()});function closeModal(){document.querySelector('#lessonModal').classList.remove('show');document.querySelector('#lessonModal').setAttribute('aria-hidden','true')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('light');document.querySelector('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾';localStorage.setItem('dmp-theme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('dmp-theme')==='light'){document.body.classList.add('light');document.querySelector('#themeBtn').textContent='☀'}
render();