-- DEPRECATED
-- Canonical profile creation/synchronization now lives in:
-- supabase/migrations/20261001_rbac_security_consolidation.sql
--
-- Do not run this file. It used to create a second auth.users trigger
-- (on_auth_user_created) alongside the canonical trigger.
-- Kept as a marker for existing deployments/history.