-- Digital Marketing Pro — Admin dashboard migration
-- Run ONLY after reviewing this file in Supabase SQL Editor.
-- This migration does not modify course_progress or certificates policies.

create table if not exists public.admin_dashboard_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_dashboard_settings enable row level security;

drop policy if exists "Admins can read dashboard settings" on public.admin_dashboard_settings;
create policy "Admins can read dashboard settings"
on public.admin_dashboard_settings
for select to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin'));

drop policy if exists "Admins can manage dashboard settings" on public.admin_dashboard_settings;
create policy "Admins can manage dashboard settings"
on public.admin_dashboard_settings
for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin'))
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin'));

-- Safe server-side user count. The browser never receives auth.users rows.
create or replace function public.admin_user_count()
returns bigint
language sql
security definer
set search_path = public, auth
as $$
  select count(*)::bigint
  from auth.users
  where coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin');
$$;

revoke all on function public.admin_user_count() from public;
revoke all on function public.admin_user_count() from anon;
grant execute on function public.admin_user_count() to authenticated;

-- IMPORTANT:
-- 1) Set your own account's app_metadata.role to 'admin' using a trusted server-side
--    Supabase mechanism/dashboard. Never accept a client-supplied role as authority.
-- 2) Premium statistics are intentionally not included until the actual payment/subscription
--    schema is confirmed.
-- 3) Do not put the service_role key in GitHub Pages or any browser JavaScript.
