-- Digital Marketing Pro — Admin/RLS foundation
-- IMPORTANT: Review this migration against the current Supabase schema before running it.
-- This file is intentionally NOT executed by the website or GitHub Pages.
-- It creates a small admin-safe table for dashboard metadata without exposing auth.users.

create table if not exists public.admin_dashboard_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_dashboard_settings enable row level security;

-- Only users whose JWT app_metadata.role is admin/super_admin can read dashboard settings.
drop policy if exists "admin dashboard settings read" on public.admin_dashboard_settings;
create policy "admin dashboard settings read"
on public.admin_dashboard_settings
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
);

-- Writes are also restricted to Admin roles.
drop policy if exists "admin dashboard settings write" on public.admin_dashboard_settings;
create policy "admin dashboard settings write"
on public.admin_dashboard_settings
for all
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
)
with check (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'super_admin')
);

-- Example metadata. Uncomment only after reviewing your production setup.
-- insert into public.admin_dashboard_settings (key, value)
-- values ('dashboard_version', '{"version":1}'::jsonb)
-- on conflict (key) do nothing;

-- NOTE:
-- Do NOT create a policy that grants browser access to auth.users.
-- User counts and other sensitive metrics should come from dedicated views/functions
-- with carefully scoped RLS or SECURITY DEFINER functions reviewed separately.
