-- Digital Marketing Pro — account settings + audit history
-- Users can safely update their own profile settings.
-- Password changes stay in Supabase Auth and are never stored in profiles.
-- Email changes are handled by Supabase Auth email confirmation.

begin;

alter table public.profiles
  add column if not exists preferred_language text not null default 'ar';

alter table public.profiles
  add constraint profiles_preferred_language_check
  check (preferred_language in ('ar','fr','en'));

create table if not exists public.profile_change_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid not null references auth.users(id) on delete cascade,
  field_name text not null,
  old_value text,
  new_value text,
  ip_address inet,
  created_at timestamptz not null default now()
);

create index if not exists profile_change_audit_user_created_idx
  on public.profile_change_audit (user_id, created_at desc);

create index if not exists profile_change_audit_created_idx
  on public.profile_change_audit (created_at desc);

alter table public.profile_change_audit enable row level security;
revoke all on public.profile_change_audit from anon, authenticated;

create or replace function public.update_my_account_settings(
  new_username text default null,
  new_date_of_birth date default null,
  new_language text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  old_profile public.profiles;
  updated_profile public.profiles;
  clean_username text;
  clean_language text;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select * into old_profile
  from public.profiles
  where id = uid
  for update;

  if not found then
    raise exception 'profile not found';
  end if;

  clean_username := nullif(trim(coalesce(new_username, old_profile.username)), '');
  clean_language := lower(coalesce(nullif(trim(new_language), ''), old_profile.preferred_language, 'ar'));

  if clean_username is not null and length(clean_username) > 40 then
    raise exception 'username too long';
  end if;

  if clean_username is not null and clean_username !~ '^[A-Za-z0-9_.-]{3,40}$' then
    raise exception 'invalid username';
  end if;

  if clean_language not in ('ar','fr','en') then
    raise exception 'invalid language';
  end if;

  if clean_username is distinct from old_profile.username then
    if exists (
      select 1 from public.profiles
      where lower(username) = lower(clean_username)
        and id <> uid
    ) then
      raise exception 'username already in use';
    end if;

    insert into public.profile_change_audit(user_id, changed_by, field_name, old_value, new_value)
    values(uid, uid, 'username', old_profile.username, clean_username);
  end if;

  if new_date_of_birth is distinct from old_profile.date_of_birth then
    insert into public.profile_change_audit(user_id, changed_by, field_name, old_value, new_value)
    values(uid, uid, 'date_of_birth', old_profile.date_of_birth::text, new_date_of_birth::text);
  end if;

  if clean_language is distinct from old_profile.preferred_language then
    insert into public.profile_change_audit(user_id, changed_by, field_name, old_value, new_value)
    values(uid, uid, 'preferred_language', old_profile.preferred_language, clean_language);
  end if;

  update public.profiles
  set username = clean_username,
      date_of_birth = new_date_of_birth,
      preferred_language = clean_language,
      updated_at = now()
  where id = uid
  returning * into updated_profile;

  return updated_profile;
end;
$$;

revoke all on function public.update_my_account_settings(text, date, text) from public, anon;
grant execute on function public.update_my_account_settings(text, date, text) to authenticated;

create or replace function public.admin_list_profile_change_audit()
returns table (
  audit_id bigint,
  user_id uuid,
  email text,
  username text,
  role text,
  field_name text,
  old_value text,
  new_value text,
  changed_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_role text := public.current_profile_role();
  actor_level integer := public.role_level(actor_role);
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if actor_role not in ('owner','admin','co_admin') then raise exception 'not authorized'; end if;

  return query
  select a.id, a.user_id, p.email, p.username, p.role,
         a.field_name, a.old_value, a.new_value, a.created_at
  from public.profile_change_audit a
  join public.profiles p on p.id = a.user_id
  where actor_role = 'owner'
     or public.role_level(p.role) < actor_level
  order by a.created_at desc;
end;
$$;

revoke all on function public.admin_list_profile_change_audit() from public, anon;
grant execute on function public.admin_list_profile_change_audit() to authenticated;

commit;
