-- Digital Marketing Pro — secure server-side IP audit + hierarchical visibility
-- Visibility: owner > admin > co_admin > administrateur > moderateur > user
-- owner sees all IPs; admin/co_admin see only strictly lower roles.
-- Raw IP is never accepted from browser JavaScript.

begin;

-- 1) Dedicated audit table. Do not put mutable security/audit data on profiles.
create table if not exists public.login_ip_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ip_address inet not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists login_ip_audit_user_created_idx
  on public.login_ip_audit (user_id, created_at desc);

create index if not exists login_ip_audit_created_idx
  on public.login_ip_audit (created_at desc);

alter table public.login_ip_audit enable row level security;

-- No direct browser access to raw audit rows.
revoke all on public.login_ip_audit from anon, authenticated;

-- 2) Server-side recorder.
-- p_ip must be supplied by a trusted server/Edge Function, never by the browser.
create or replace function public.record_login_ip(
  p_user_id uuid,
  p_ip inet,
  p_user_agent text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  audit_id bigint;
begin
  if p_user_id is null or p_ip is null then
    raise exception 'invalid audit data';
  end if;

  insert into public.login_ip_audit (user_id, ip_address, user_agent)
  values (
    p_user_id,
    p_ip,
    left(nullif(trim(coalesce(p_user_agent, '')), ''), 1000)
  )
  returning id into audit_id;

  return audit_id;
end;
$$;

revoke all on function public.record_login_ip(uuid, inet, text) from public, anon, authenticated;

-- 3) Hierarchical read RPC.
-- Owner: all users.
-- Admin: strictly lower roles.
-- Co-admin: strictly lower roles.
-- Other roles: no IP access.
create or replace function public.admin_list_login_ips()
returns table (
  audit_id bigint,
  user_id uuid,
  email text,
  username text,
  role text,
  ip_address inet,
  user_agent text,
  logged_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_role text;
  actor_level integer;
begin
  if (select auth.uid()) is null then
    raise exception 'not authenticated';
  end if;

  actor_role := public.current_profile_role();
  actor_level := public.role_level(actor_role);

  if actor_role not in ('owner', 'admin', 'co_admin') then
    raise exception 'not authorized';
  end if;

  return query
  select
    a.id,
    a.user_id,
    p.email,
    p.username,
    p.role,
    a.ip_address,
    a.user_agent,
    a.created_at
  from public.login_ip_audit a
  join public.profiles p on p.id = a.user_id
  where actor_role = 'owner'
     or public.role_level(p.role) < actor_level
  order by a.created_at desc;
end;
$$;

revoke all on function public.admin_list_login_ips() from public, anon;
grant execute on function public.admin_list_login_ips() to authenticated;

-- 4) Convenient latest-IP RPC for the admin UI.
create or replace function public.admin_latest_login_ips()
returns table (
  user_id uuid,
  email text,
  username text,
  role text,
  ip_address inet,
  logged_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_role text;
  actor_level integer;
begin
  if (select auth.uid()) is null then
    raise exception 'not authenticated';
  end if;

  actor_role := public.current_profile_role();
  actor_level := public.role_level(actor_role);

  if actor_role not in ('owner', 'admin', 'co_admin') then
    raise exception 'not authorized';
  end if;

  return query
  select distinct on (p.id)
    p.id,
    p.email,
    p.username,
    p.role,
    a.ip_address,
    a.created_at
  from public.profiles p
  join public.login_ip_audit a on a.user_id = p.id
  where actor_role = 'owner'
     or public.role_level(p.role) < actor_level
  order by p.id, a.created_at desc;
end;
$$;

revoke all on function public.admin_latest_login_ips() from public, anon;
grant execute on function public.admin_latest_login_ips() to authenticated;

commit;
